Repository googleapis/python-resource-settings, pull requests merged in 2021-08, with the labels that each got.

#27 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: resourcesettings, automerge, cla: yes

#32 chore: fix broken links in README
  README.rst
Labels: cla: yes, api: resourcesettings, automerge: exact

#35 chore: migrate default branch from master to main
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: cla: yes, api: resourcesettings
